<img src = "https://i.imgur.com/AKXoLze.jpg"  align = "center">

Numpy eigenvalues and eigenvectors
We calculate the eigenvalues and eigenvectors of the matrix 

<img src = "http://www.physics.utah.edu/~detar/lessons/python/numpy_eigen/img1.png" style="width: 350px;"/>


In [1]:
import numpy as np
from numpy import linalg as LA
A = np.array([[1,-2],[1,4]])
w, v = LA.eig(A)
print(w)
print(v)
p=5**0.5
q=1/p
q


[2. 3.]
[[-0.89442719  0.70710678]
 [ 0.4472136  -0.70710678]]


0.4472135954999579

The numpy.linalg.eig function returns a tuple consisting of a vector and an array. The vector (here w) contains the eigenvalues. The array (here v) contains the corresponding eigenvectors, one eigenvector per column. The eigenvectors are normalized so their Euclidean norms are 1.

The eigenvalue w[0] goes with the 0th column of v. The eigenvalue w[1] goes with column 1, etc. To extract the ith column vector, we use 

In [2]:
i = 1
u = v[:,i]
print(u)

[ 0.70710678 -0.70710678]


Just to be clear about what is happening here, let's check the eigenvector/eigenvalue condition for the second eigenvalue and eigenvector. 

<img src = "http://www.physics.utah.edu/~detar/lessons/python/numpy_eigen/img2.png" style="width: 350px;"/>

where $u$ is the eigenvector and $\lambda$ is its eigenvalue. So we multiply the eigenvector v[:,1] by A and check that it is the same as multiplying the same eigenvector by its eigenvalue w[1]. 

In [3]:
u = v[:,1]
print(u)
lam = w[1]
print(lam)
print(np.dot(A,u))
print(lam*u)

[ 0.70710678 -0.70710678]
3.0
[ 2.12132034 -2.12132034]
[ 2.12132034 -2.12132034]


We see that the results are the same, as they should be

The numpy linalg package does not sort eigenvalues and eigenvectors. Sometimes it is useful to put the eigenvalues in ascending order. But when we do, we might also want to rearrange the eigenvectors so they still go with the eigenvalues. We do this using an indirect sort, provided by the numpy argsort() function. An indirect sort generates a list of indices that wouuld put the values in order, but it doesn't actually do the sort. So, for example if we want to sort the numbers w = [4.2, 2.1, 5.7] in ascending order, taking terms with indices [1, 0, 2], that is [w[1], w[0], w[2]], puts them in order. The indirect sort gives us just the list of indices. Here is how we can use it: 

In [4]:
w, v = LA.eig(A)
print(w)
print(v)
idx = np.argsort(w)
w = w[idx]
v = v[:,idx]
print(w)
print(v)

[2. 3.]
[[-0.89442719  0.70710678]
 [ 0.4472136  -0.70710678]]
[2. 3.]
[[-0.89442719  0.70710678]
 [ 0.4472136  -0.70710678]]


The indices go into the numpy array idx, and we use them to rearrange the eigenvalues and eigenvectors at the same time so we keep the correspondence between eigenvalues and their eigenvectors.